name: Build project
on: push
permissions:
  contents: read
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup Java toolchains
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: |
            8
            11
            17

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --info --stacktrace

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/libs/
            build/reports/
